#!/bin/bash

PROJECT_OWNER="${PROJECT_OWNER:-oversizedev}"
PROJECT_NUMBER="${PROJECT_NUMBER:?Set PROJECT_NUMBER to the ___PACKAGENAME___ GitHub Project number}"
REPO="${REPO:-oversizedev/___PACKAGENAME___}"

AUTO_LABEL="${AUTO_LABEL:-agent:auto}"
TASK_LABEL="${TASK_LABEL:-agent:task}"
EPIC_LABEL="${EPIC_LABEL:-agent:epic}"

PLANNER_MAX_TURNS="${PLANNER_MAX_TURNS:-60}"
TEAM_LEAD_MAX_TURNS="${TEAM_LEAD_MAX_TURNS:-180}"

RUNTIME_DIR="${RUNTIME_DIR:-${TMPDIR:-/tmp}/___PACKAGENAME:identifier___-agent-team}"

export CLAUDE_CODE_PRINT_BG_WAIT_CEILING_MS="${CLAUDE_CODE_PRINT_BG_WAIT_CEILING_MS:-0}"
