name: ___VARIABLE_productName:RFC1034Identifier___
options:
  bundleIdPrefix: ___VARIABLE_bundleIdentifierPrefix:bundleIdentifier___
  xcodeVersion: 15.2
  deploymentTarget:
    iOS: 17.2
  groupSortPosition: top
  generateEmptyDirectories: true
  findCarthageFrameworks: true
  minimumXcodeGenVersion: 2.3.0

configs:
  Debug: debug
  Release: release

include:
  - ___VARIABLE_productName:RFC1034Identifier___/App/LocalPackages.yml
  - ___VARIABLE_productName:RFC1034Identifier___/App/Targets.yml
  - ___VARIABLE_productName:RFC1034Identifier___/App/Settings.yml
