settings:
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
  ENABLE_USER_SCRIPT_SANDBOXING: NO
  LOCALIZATION_PREFERS_STRING_CATALOGS: YES
  ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
  ASSETCATALOG_COMPILER_ALTERNATE_APPICON_NAMES: AlternateAppIcon1 AlternateAppIcon2 AlternateAppIcon3 AlternateAppIcon4 AlternateAppIcon5 AlternateAppIcon6 AlternateAppIcon7
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
  DEVELOPMENT_TEAM: ER582ZK85C
  GENERATE_INFOPLIST_FILE: YES
  TARGETED_DEVICE_FAMILY: "1,2"
  ENABLE_PREVIEWS: YES
  DEVELOPMENT_ASSET_PATHS: "\"___VARIABLE_productName:RFC1034Identifier___/Resources\""
  IPHONEOS_DEPLOYMENT_TARGET: 17.0
  CODE_SIGN_IDENTITY: "Apple Development"
  GCC_C_LANGUAGE_STANDARD: gnu17
  CLANG_CXX_LANGUAGE_STANDARD: gnu++20
  SWIFT_EMIT_LOC_STRINGS: YES
  CURRENT_PROJECT_VERSION: 1
  MARKETING_VERSION: 1.0
