options:
  bundleIdPrefix: ___VARIABLE_bundleIdentifierPrefix:bundleIdentifier___
  xcodeVersion: 27.0
  deploymentTarget:
    iOS: 18.0
    macOS: 15.0
    tvOS: 18.0
    watchOS: 11.0
    visionOS: 2.0
  groupSortPosition: top
  generateEmptyDirectories: true
  findCarthageFrameworks: true
  minimumXcodeGenVersion: 2.44.1
  fileTypes:
    "icon":
      file: true

configs:
  Debug: debug
  AppStore: release

fileGroups:
  - ../Configs
