#!/usr/bin/env python3

import re
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
DELIMITER = "PACKAGE_FILE_EOF"

SCRIPTS = {
    "init_packages.sh": {
        "description": "Package manifests for all local packages",
        "matches": lambda path: path.name in ("Package.swift", ".gitignore"),
    },
    "init_packages_files.sh": {
        "description": "Env and App sources",
        "matches": lambda path: path.parts[1] in ("Env", "App") and path.name not in ("Package.swift", ".gitignore"),
    },
    "init_packages_swiftdata_files.sh": {
        "description": "Models, Database and Services sources",
        "matches": lambda path: path.parts[1] in ("Models", "Database", "Services")
        and path.name not in ("Package.swift", ".gitignore"),
    },
}

HEADER_DATE = re.compile(r"^(// .+, created on )\d{2}\.\d{2}\.\d{4}$", re.MULTILINE)
HEADER_YEAR = re.compile(r"^(// Copyright © )\d{4}( .+)$", re.MULTILINE)


def package_files() -> list[Path]:
    output = subprocess.run(
        ["git", "ls-files", "--cached", "--others", "--exclude-standard", "Packages"],
        cwd=PROJECT_ROOT,
        check=True,
        capture_output=True,
        text=True,
    ).stdout
    files = []
    for line in output.splitlines():
        path = Path(line)
        if not (PROJECT_ROOT / path).is_file():
            continue
        if any(part in (".build", ".swiftpm") for part in path.parts) or path.name == "Package.resolved":
            continue
        files.append(path)
    return sorted(files)


def render(script_name: str, description: str, files: list[Path]) -> str:
    lines = [
        "#!/bin/bash",
        "",
        f"# Generated by scripts/generate_init_scripts.py — {description}.",
        "# Do not edit by hand: change Packages/ and run `make init-scripts`.",
        "",
        "set -euo pipefail",
        "",
        'YEAR="${INIT_YEAR:-$(date +%Y)}"',
        'TODAY="${INIT_DATE:-$(date +%d.%m.%Y)}"',
        "",
    ]
    for path in files:
        content = (PROJECT_ROOT / path).read_text()
        if DELIMITER in content:
            raise SystemExit(f"{path} contains the heredoc delimiter")
        content = HEADER_DATE.sub(r"\g<1>__INIT_DATE__", content)
        content = HEADER_YEAR.sub(r"\g<1>__INIT_YEAR__\g<2>", content)
        if not content.endswith("\n"):
            content += "\n"
        lines.append(f'mkdir -p "{path.parent}"')
        lines.append(f"cat <<'{DELIMITER}' >\"{path}\"")
        lines.append(content.rstrip("\n"))
        lines.append(DELIMITER)
        lines.append("")
    lines.append("find Packages -name '*.swift' -type f -exec sed -i '' \\")
    lines.append('    -e "s/__INIT_DATE__/$TODAY/" \\')
    lines.append('    -e "s/__INIT_YEAR__/$YEAR/" {} +')
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    files = package_files()
    assigned: set[Path] = set()
    for script_name, config in SCRIPTS.items():
        selected = [path for path in files if config["matches"](path)]
        assigned.update(selected)
        script_path = SCRIPTS_DIR / script_name
        script_path.write_text(render(script_name, config["description"], selected))
        script_path.chmod(0o755)
        print(f"{script_name}: {len(selected)} files")
    unassigned = [path for path in files if path not in assigned]
    if unassigned:
        raise SystemExit("Files not covered by any init script:\n" + "\n".join(map(str, unassigned)))


if __name__ == "__main__":
    main()
