#!/bin/bash

# Generated by scripts/generate_init_scripts.py — Package manifests for all local packages.
# Do not edit by hand: change Packages/ and run `make init-scripts`.

set -euo pipefail

YEAR="${INIT_YEAR:-$(date +%Y)}"
TODAY="${INIT_DATE:-$(date +%d.%m.%Y)}"

mkdir -p "Packages/App"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/.gitignore"
.DS_Store
/.build
/Packages
xcuserdata/
DerivedData/
.swiftpm/configuration/registries.json
.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
.netrc
PACKAGE_FILE_EOF

mkdir -p "Packages/App"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Package.swift"
// swift-tools-version: 6.1

import Foundation
import PackageDescription

let commonDependencies: [PackageDescription.Package.Dependency] = [
    .package(name: "Models", path: "../Models"),
    .package(name: "Database", path: "../Database"),
    .package(name: "Env", path: "../Env"),
    .package(name: "Services", path: "../Services"),
    .package(url: "https://github.com/hmlongco/Factory.git", .upToNextMajor(from: "3.0.2")),
    .package(url: "https://github.com/fatbobman/ObservableDefaults.git", .upToNextMinor(from: "1.6.0")),
]

let remoteDependencies: [PackageDescription.Package.Dependency] = commonDependencies + [
    .package(url: "https://github.com/oversizedev/OversizeLocalizable.git", .upToNextMajor(from: "1.4.0")),
    .package(url: "https://github.com/oversizedev/OversizeResources.git", .upToNextMajor(from: "2.0.0")),
    .package(url: "https://github.com/oversizedev/OversizeCore.git", .upToNextMajor(from: "1.3.0")),
    .package(url: "https://github.com/oversizedev/OversizeKit.git", .upToNextMajor(from: "3.0.0")),
    .package(url: "https://github.com/oversizedev/OversizeUI.git", .upToNextMajor(from: "3.20.4")),
    .package(url: "https://github.com/oversizedev/OversizeServices.git", .upToNextMajor(from: "1.4.0")),
    .package(url: "https://github.com/oversizedev/OversizeNavigation.git", .upToNextMajor(from: "0.9.0")),
    .package(url: "https://github.com/oversizedev/OversizeArchitecture.git", .upToNextMajor(from: "0.2.0")),
]

let sharedPackagesPath = "\(NSHomeDirectory())/Developer/Packages"

let localDependencies: [PackageDescription.Package.Dependency] = commonDependencies + [
    .package(name: "OversizeLocalizable", path: "\(sharedPackagesPath)/OversizeLocalizable"),
    .package(name: "OversizeResources", path: "\(sharedPackagesPath)/OversizeResources"),
    .package(name: "OversizeCore", path: "\(sharedPackagesPath)/OversizeCore"),
    .package(name: "OversizeKit", path: "\(sharedPackagesPath)/OversizeKit"),
    .package(name: "OversizeUI", path: "\(sharedPackagesPath)/OversizeUI"),
    .package(name: "OversizeServices", path: "\(sharedPackagesPath)/OversizeServices"),
    .package(name: "OversizeNavigation", path: "\(sharedPackagesPath)/OversizeNavigation"),
    .package(name: "OversizeArchitecture", path: "\(sharedPackagesPath)/OversizeArchitecture"),
]

let isLocalDev = ProcessInfo.processInfo.environment["FORCE_REMOTE_PACKAGES"] != "1"
    && FileManager.default.fileExists(atPath: "\(sharedPackagesPath)/OversizeCore")
let dependencies: [PackageDescription.Package.Dependency] = isLocalDev ? localDependencies : remoteDependencies

let package = Package(
    name: "App",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v18),
        .macOS(.v15),
        .tvOS(.v18),
        .watchOS(.v11),
        .visionOS(.v2),
    ],
    products: [
        .library(name: "Main", targets: ["Main"]),
        .library(name: "Onboarding", targets: ["Onboarding"]),
        .library(name: "Settings", targets: ["Settings"]),
    ],
    dependencies: dependencies,
    targets: [
        .target(
            name: "Main",
            dependencies: [
                .product(name: "Models", package: "Models"),
                .product(name: "Database", package: "Database"),
                .product(name: "Env", package: "Env"),
                .product(name: "Services", package: "Services"),
                .product(name: "OversizeResources", package: "OversizeResources"),
                .product(name: "OversizeCore", package: "OversizeCore"),
                .product(name: "OversizeLocalizable", package: "OversizeLocalizable"),
                .product(name: "OversizeKit", package: "OversizeKit"),
                .product(name: "OversizeServices", package: "OversizeServices"),
                .product(name: "OversizeStoreService", package: "OversizeServices"),
                .product(name: "FactoryKit", package: "Factory"),
                .product(name: "OversizeUI", package: "OversizeUI"),
                .product(name: "OversizeNoticeKit", package: "OversizeKit"),
                .product(name: "OversizeNavigation", package: "OversizeNavigation"),
                .product(name: "ObservableDefaults", package: "ObservableDefaults"),
                .product(name: "OversizeArchitecture", package: "OversizeArchitecture"),
            ]
        ),
        .target(
            name: "Onboarding",
            dependencies: [
                .product(name: "Env", package: "Env"),
                .product(name: "OversizeOnboardingKit", package: "OversizeKit"),
                .product(name: "OversizeUI", package: "OversizeUI"),
                .product(name: "OversizeServices", package: "OversizeServices"),
                .product(name: "OversizeNavigation", package: "OversizeNavigation"),
                .product(name: "OversizeArchitecture", package: "OversizeArchitecture"),
                .product(name: "OversizeCore", package: "OversizeCore"),
                .product(name: "FactoryKit", package: "Factory"),
            ]
        ),
        .target(
            name: "Settings",
            dependencies: [
                .product(name: "Env", package: "Env"),
                .product(name: "OversizeKit", package: "OversizeKit"),
                .product(name: "OversizeResources", package: "OversizeResources"),
                .product(name: "OversizeUI", package: "OversizeUI"),
                .product(name: "OversizeArchitecture", package: "OversizeArchitecture"),
                .product(name: "OversizeNavigation", package: "OversizeNavigation"),
            ]
        ),
        .testTarget(
            name: "MainTests",
            dependencies: [
                "Main",
                .product(name: "Models", package: "Models"),
                .product(name: "Database", package: "Database"),
                .product(name: "Services", package: "Services"),
                .product(name: "FactoryKit", package: "Factory"),
                .product(name: "FactoryTesting", package: "Factory"),
            ]
        ),
    ]
)
PACKAGE_FILE_EOF

mkdir -p "Packages/Database"
cat <<'PACKAGE_FILE_EOF' >"Packages/Database/.gitignore"
.DS_Store
/.build
/Packages
xcuserdata/
DerivedData/
.swiftpm/configuration/registries.json
.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
.netrc
PACKAGE_FILE_EOF

mkdir -p "Packages/Database"
cat <<'PACKAGE_FILE_EOF' >"Packages/Database/Package.swift"
// swift-tools-version: 6.1

import Foundation
import PackageDescription

let commonDependencies: [PackageDescription.Package.Dependency] = [
    .package(name: "Models", path: "../Models"),
    .package(url: "https://github.com/hmlongco/Factory.git", .upToNextMajor(from: "3.0.2")),
]

let remoteDependencies: [PackageDescription.Package.Dependency] = commonDependencies + [
    .package(url: "https://github.com/oversizedev/OversizeCore.git", .upToNextMajor(from: "1.3.0")),
]

let sharedPackagesPath = "\(NSHomeDirectory())/Developer/Packages"

let localDependencies: [PackageDescription.Package.Dependency] = commonDependencies + [
    .package(name: "OversizeCore", path: "\(sharedPackagesPath)/OversizeCore"),
]

let isLocalDev = ProcessInfo.processInfo.environment["FORCE_REMOTE_PACKAGES"] != "1"
    && FileManager.default.fileExists(atPath: "\(sharedPackagesPath)/OversizeCore")
let dependencies: [PackageDescription.Package.Dependency] = isLocalDev ? localDependencies : remoteDependencies

let package = Package(
    name: "Database",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v18),
        .macOS(.v15),
        .tvOS(.v18),
        .watchOS(.v11),
        .visionOS(.v2),
    ],
    products: [
        .library(
            name: "Database",
            targets: ["Database"]
        ),
    ],
    dependencies: dependencies,
    targets: [
        .target(
            name: "Database",
            dependencies: [
                .product(name: "Models", package: "Models"),
                .product(name: "OversizeCore", package: "OversizeCore"),
                .product(name: "FactoryKit", package: "Factory"),
            ]
        ),
        .testTarget(
            name: "DatabaseTests",
            dependencies: [
                "Database",
                .product(name: "Models", package: "Models"),
                .product(name: "OversizeCore", package: "OversizeCore"),
            ]
        ),
    ]
)
PACKAGE_FILE_EOF

mkdir -p "Packages/Env"
cat <<'PACKAGE_FILE_EOF' >"Packages/Env/.gitignore"
.DS_Store
/.build
/Packages
xcuserdata/
DerivedData/
.swiftpm/configuration/registries.json
.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
.netrc
PACKAGE_FILE_EOF

mkdir -p "Packages/Env"
cat <<'PACKAGE_FILE_EOF' >"Packages/Env/Package.swift"
// swift-tools-version: 6.1

import Foundation
import PackageDescription

let remoteDependencies: [PackageDescription.Package.Dependency] = [
    .package(name: "Models", path: "../Models"),
    .package(url: "https://github.com/oversizedev/OversizeResources.git", .upToNextMajor(from: "2.0.0")),
    .package(url: "https://github.com/oversizedev/OversizeUI.git", .upToNextMajor(from: "3.20.4")),
    .package(url: "https://github.com/oversizedev/OversizeArchitecture.git", .upToNextMajor(from: "0.2.0")),
]

let sharedPackagesPath = "\(NSHomeDirectory())/Developer/Packages"

let localDependencies: [PackageDescription.Package.Dependency] = [
    .package(name: "Models", path: "../Models"),
    .package(name: "OversizeResources", path: "\(sharedPackagesPath)/OversizeResources"),
    .package(name: "OversizeUI", path: "\(sharedPackagesPath)/OversizeUI"),
    .package(name: "OversizeArchitecture", path: "\(sharedPackagesPath)/OversizeArchitecture"),
]

let isLocalDev = ProcessInfo.processInfo.environment["FORCE_REMOTE_PACKAGES"] != "1"
    && FileManager.default.fileExists(atPath: "\(sharedPackagesPath)/OversizeCore")
let dependencies: [PackageDescription.Package.Dependency] = isLocalDev ? localDependencies : remoteDependencies

let package = Package(
    name: "Env",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v18),
        .macOS(.v15),
        .tvOS(.v18),
        .watchOS(.v11),
        .visionOS(.v2),
    ],
    products: [
        .library(
            name: "Env",
            targets: ["Env"]
        ),
    ],
    dependencies: dependencies,
    targets: [
        .target(
            name: "Env",
            dependencies: [
                .product(name: "Models", package: "Models"),
                .product(name: "OversizeResources", package: "OversizeResources"),
                .product(name: "OversizeUI", package: "OversizeUI"),
                .product(name: "OversizeArchitecture", package: "OversizeArchitecture"),
            ]
        ),
    ]
)
PACKAGE_FILE_EOF

mkdir -p "Packages/Models"
cat <<'PACKAGE_FILE_EOF' >"Packages/Models/.gitignore"
.DS_Store
/.build
/Packages
xcuserdata/
DerivedData/
.swiftpm/configuration/registries.json
.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
.netrc
PACKAGE_FILE_EOF

mkdir -p "Packages/Models"
cat <<'PACKAGE_FILE_EOF' >"Packages/Models/Package.swift"
// swift-tools-version: 6.1

import Foundation
import PackageDescription

let remoteDependencies: [PackageDescription.Package.Dependency] = [
    .package(url: "https://github.com/oversizedev/OversizeCore.git", .upToNextMajor(from: "1.3.0")),
]

let sharedPackagesPath = "\(NSHomeDirectory())/Developer/Packages"

let localDependencies: [PackageDescription.Package.Dependency] = [
    .package(name: "OversizeCore", path: "\(sharedPackagesPath)/OversizeCore"),
]

let isLocalDev = ProcessInfo.processInfo.environment["FORCE_REMOTE_PACKAGES"] != "1"
    && FileManager.default.fileExists(atPath: "\(sharedPackagesPath)/OversizeCore")
let dependencies: [PackageDescription.Package.Dependency] = isLocalDev ? localDependencies : remoteDependencies

let package = Package(
    name: "Models",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v18),
        .macOS(.v15),
        .tvOS(.v18),
        .watchOS(.v11),
        .visionOS(.v2),
    ],
    products: [
        .library(
            name: "Models",
            targets: ["Models"]
        ),
    ],
    dependencies: dependencies,
    targets: [
        .target(
            name: "Models",
            dependencies: [
                .product(name: "OversizeCore", package: "OversizeCore"),
            ]
        ),
    ]
)
PACKAGE_FILE_EOF

mkdir -p "Packages/Services"
cat <<'PACKAGE_FILE_EOF' >"Packages/Services/.gitignore"
.DS_Store
/.build
/Packages
xcuserdata/
DerivedData/
.swiftpm/configuration/registries.json
.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
.netrc
PACKAGE_FILE_EOF

mkdir -p "Packages/Services"
cat <<'PACKAGE_FILE_EOF' >"Packages/Services/Package.swift"
// swift-tools-version: 6.1

import Foundation
import PackageDescription

let commonDependencies: [PackageDescription.Package.Dependency] = [
    .package(name: "Models", path: "../Models"),
    .package(name: "Database", path: "../Database"),
    .package(url: "https://github.com/hmlongco/Factory.git", .upToNextMajor(from: "3.0.2")),
]

let remoteDependencies: [PackageDescription.Package.Dependency] = commonDependencies + [
    .package(url: "https://github.com/oversizedev/OversizeCore.git", .upToNextMajor(from: "1.3.0")),
]

let sharedPackagesPath = "\(NSHomeDirectory())/Developer/Packages"

let localDependencies: [PackageDescription.Package.Dependency] = commonDependencies + [
    .package(name: "OversizeCore", path: "\(sharedPackagesPath)/OversizeCore"),
]

let isLocalDev = ProcessInfo.processInfo.environment["FORCE_REMOTE_PACKAGES"] != "1"
    && FileManager.default.fileExists(atPath: "\(sharedPackagesPath)/OversizeCore")
let dependencies: [PackageDescription.Package.Dependency] = isLocalDev ? localDependencies : remoteDependencies

let package = Package(
    name: "Services",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v18),
        .macOS(.v15),
        .tvOS(.v18),
        .watchOS(.v11),
        .visionOS(.v2),
    ],
    products: [
        .library(
            name: "Services",
            targets: ["Services"]
        ),
    ],
    dependencies: dependencies,
    targets: [
        .target(
            name: "Services",
            dependencies: [
                .product(name: "Models", package: "Models"),
                .product(name: "Database", package: "Database"),
                .product(name: "OversizeCore", package: "OversizeCore"),
                .product(name: "FactoryKit", package: "Factory"),
            ]
        ),
        .testTarget(
            name: "ServicesTests",
            dependencies: [
                "Services",
                .product(name: "Models", package: "Models"),
                .product(name: "FactoryKit", package: "Factory"),
                .product(name: "FactoryTesting", package: "Factory"),
            ]
        ),
    ]
)
PACKAGE_FILE_EOF

find Packages -name '*.swift' -type f -exec sed -i '' \
    -e "s/__INIT_DATE__/$TODAY/" \
    -e "s/__INIT_YEAR__/$YEAR/" {} +
