#!/bin/bash

# Generated by scripts/generate_init_scripts.py — Models, Database and Services sources.
# Do not edit by hand: change Packages/ and run `make init-scripts`.

set -euo pipefail

YEAR="${INIT_YEAR:-$(date +%Y)}"
TODAY="${INIT_DATE:-$(date +%d.%m.%Y)}"

mkdir -p "Packages/Database/Sources/Database/Entities"
cat <<'PACKAGE_FILE_EOF' >"Packages/Database/Sources/Database/Entities/___VARIABLE_modelName___Entity.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___Entity.swift, created on __INIT_DATE__
//

import Foundation
import OversizeCore
import SwiftData

@Model
final class ___VARIABLE_modelName___Entity {
    private(set) var id: UUID = UUID()

    var name: String = ""

    var colorData: ColorData?

    @Attribute(.externalStorage)
    var imageData: Data?

    var date: Date = Date.now

    var note: String?

    var isFavorite: Bool = false

    var isArchive: Bool = false

    init(id: UUID = UUID()) {
        self.id = id
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/Database/Sources/Database/Injection"
cat <<'PACKAGE_FILE_EOF' >"Packages/Database/Sources/Database/Injection/Injection.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// Injection.swift, created on __INIT_DATE__
//

import FactoryKit
import Foundation
import OversizeCore
import SwiftData

public extension Container {
    var modelContainerService: Factory<ModelContainer> {
        self {
            ModelContainer.make(inMemory: false)
        }
        .onPreview {
            ModelContainer.make(inMemory: true)
        }
        .onTest {
            ModelContainer.make(inMemory: true)
        }
        .cached
    }

    var storageService: Factory<___VARIABLE_modelName___StorageService> {
        self {
            ___VARIABLE_modelName___StorageService(modelContainer: self.modelContainerService())
        }.cached
    }
}

// MARK: - ModelContainer

extension ModelContainer {
    private static let cloudKitEnabledKey = "SettingsStore.cloudKitEnabled"

    static var schema: Schema {
        Schema([___VARIABLE_modelName___Entity.self])
    }

    static func make(inMemory: Bool) -> ModelContainer {
        if inMemory {
            return makeOrFail(ModelConfiguration(schema: schema, isStoredInMemoryOnly: true))
        }

        let cloudKitEnabled = UserDefaults.standard.bool(forKey: cloudKitEnabledKey)
        let configuration = ModelConfiguration(
            schema: schema,
            cloudKitDatabase: cloudKitEnabled ? .automatic : .none
        )
        do {
            return try ModelContainer(for: schema, configurations: [configuration])
        } catch {
            Log.error("Primary ModelContainer failed, falling back to local storage:", error: error)
            return makeOrFail(ModelConfiguration(schema: schema, cloudKitDatabase: .none))
        }
    }

    private static func makeOrFail(_ configuration: ModelConfiguration) -> ModelContainer {
        do {
            return try ModelContainer(for: schema, configurations: [configuration])
        } catch {
            Log.error("ModelContainer initialization failed:", error: error)
            preconditionFailure("ModelContainer initialization failed: \(error)")
        }
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/Database/Sources/Database/Mapping"
cat <<'PACKAGE_FILE_EOF' >"Packages/Database/Sources/Database/Mapping/___VARIABLE_modelName___Mapping.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___Mapping.swift, created on __INIT_DATE__
//

import Foundation
import Models
import OversizeCore

extension ___VARIABLE_modelName___ {
    init(from entity: ___VARIABLE_modelName___Entity) {
        self.init(
            id: entity.id,
            imageData: entity.imageData,
            name: entity.name,
            color: entity.colorData?.color ?? .clear,
            date: entity.date,
            note: entity.note,
            isFavorite: entity.isFavorite,
            isArchive: entity.isArchive
        )
    }
}

extension ___VARIABLE_modelName___Entity {
    convenience init(from domain: ___VARIABLE_modelName___) {
        self.init(id: domain.id)
        apply(domain)
    }

    func apply(_ domain: ___VARIABLE_modelName___) {
        name = domain.name
        colorData = ColorData(color: domain.color)
        imageData = domain.imageData
        date = domain.date
        note = domain.note
        isFavorite = domain.isFavorite
        isArchive = domain.isArchive
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/Database/Sources/Database/Services"
cat <<'PACKAGE_FILE_EOF' >"Packages/Database/Sources/Database/Services/___VARIABLE_modelName___StorageService.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___StorageService.swift, created on __INIT_DATE__
//

import Foundation
import Models
import OversizeCore
import SwiftData

@ModelActor
public actor ___VARIABLE_modelName___StorageService {
    public func fetch() throws -> [___VARIABLE_modelName___] {
        let descriptor = FetchDescriptor<___VARIABLE_modelName___Entity>(sortBy: [SortDescriptor(\.date, order: .reverse)])
        do {
            return try modelContext.fetch(descriptor).map { ___VARIABLE_modelName___(from: $0) }
        } catch {
            Log.error("Fetch ___VARIABLE_modelPluralVariableName___ failed:", error: error)
            throw PersistenceError.fetchFailed
        }
    }

    public func fetch(id: UUID) throws -> ___VARIABLE_modelName___ {
        try ___VARIABLE_modelName___(from: fetchEntity(id: id))
    }

    @discardableResult
    public func save(_ ___VARIABLE_modelVariableName___: ___VARIABLE_modelName___) throws -> ___VARIABLE_modelName___ {
        let entity = ___VARIABLE_modelName___Entity(from: ___VARIABLE_modelVariableName___)
        modelContext.insert(entity)
        try saveContext(failure: .saveFailed)
        return ___VARIABLE_modelName___(from: entity)
    }

    @discardableResult
    public func update(_ ___VARIABLE_modelVariableName___: ___VARIABLE_modelName___) throws -> ___VARIABLE_modelName___ {
        let entity = try fetchEntity(id: ___VARIABLE_modelVariableName___.id)
        entity.apply(___VARIABLE_modelVariableName___)
        try saveContext(failure: .updateFailed)
        return ___VARIABLE_modelName___(from: entity)
    }

    public func delete(id: UUID) throws {
        let entity = try fetchEntity(id: id)
        modelContext.delete(entity)
        try saveContext(failure: .deleteFailed)
    }
}

// MARK: - Helpers

private extension ___VARIABLE_modelName___StorageService {
    func fetchEntity(id: UUID) throws -> ___VARIABLE_modelName___Entity {
        var descriptor = FetchDescriptor<___VARIABLE_modelName___Entity>(predicate: #Predicate { $0.id == id })
        descriptor.fetchLimit = 1
        let entity: ___VARIABLE_modelName___Entity?
        do {
            entity = try modelContext.fetch(descriptor).first
        } catch {
            Log.error("Fetch ___VARIABLE_modelName___ \(id) failed:", error: error)
            throw PersistenceError.fetchFailed
        }
        guard let entity else {
            throw PersistenceError.itemNotFound
        }
        return entity
    }

    func saveContext(failure: PersistenceError) throws {
        do {
            try modelContext.save()
        } catch {
            modelContext.rollback()
            Log.error("Save context failed:", error: error)
            throw failure
        }
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/Database/Tests/DatabaseTests"
cat <<'PACKAGE_FILE_EOF' >"Packages/Database/Tests/DatabaseTests/___VARIABLE_modelName___StorageServiceTests.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___StorageServiceTests.swift, created on __INIT_DATE__
//

@testable import Database
import Foundation
import Models
import OversizeCore
import SwiftData
import SwiftUI
import Testing

struct ___VARIABLE_modelName___StorageServiceTests {
    private let storage = ___VARIABLE_modelName___StorageService(modelContainer: .make(inMemory: true))

    @Test func `save and fetch by id`() async throws {
        let ___VARIABLE_modelVariableName___ = ___VARIABLE_modelName___(name: "Music", color: .pink, date: .now, note: "Family plan")

        try await storage.save(___VARIABLE_modelVariableName___)
        let fetched = try await storage.fetch(id: ___VARIABLE_modelVariableName___.id)

        #expect(fetched.name == "Music")
        #expect(fetched.note == "Family plan")
        #expect(try await storage.fetch().count == 1)
    }

    @Test func `fetch sorts by date descending`() async throws {
        try await storage.save(___VARIABLE_modelName___(name: "Older", color: .blue, date: .now.addingTimeInterval(-3600)))
        try await storage.save(___VARIABLE_modelName___(name: "Newer", color: .green, date: .now))

        let names = try await storage.fetch().map(\.name)

        #expect(names == ["Newer", "Older"])
    }

    @Test func `update replaces all fields`() async throws {
        let ___VARIABLE_modelVariableName___ = ___VARIABLE_modelName___(name: "Video", color: .red, date: .now, note: "Family plan", isFavorite: true)
        try await storage.save(___VARIABLE_modelVariableName___)

        let changed = ___VARIABLE_modelName___(id: ___VARIABLE_modelVariableName___.id, name: "Video HD", color: .red, date: ___VARIABLE_modelVariableName___.date)
        try await storage.update(changed)
        let fetched = try await storage.fetch(id: ___VARIABLE_modelVariableName___.id)

        #expect(fetched.name == "Video HD")
        #expect(fetched.note == nil)
        #expect(fetched.isFavorite == false)
    }

    @Test func `delete removes ___VARIABLE_modelVariableName___`() async throws {
        let ___VARIABLE_modelVariableName___ = ___VARIABLE_modelName___(name: "Cloud", color: .orange, date: .now)
        try await storage.save(___VARIABLE_modelVariableName___)

        try await storage.delete(id: ___VARIABLE_modelVariableName___.id)

        #expect(try await storage.fetch().isEmpty)
    }

    @Test func `missing ___VARIABLE_modelVariableName___ throws item not found`() async {
        let missing = ___VARIABLE_modelName___(name: "Missing", color: .gray, date: .now)

        await expectItemNotFound { _ = try await storage.fetch(id: missing.id) }
        await expectItemNotFound { try await storage.update(missing) }
        await expectItemNotFound { try await storage.delete(id: missing.id) }
    }
}

// MARK: - Helpers

private extension ___VARIABLE_modelName___StorageServiceTests {
    func expectItemNotFound(_ operation: () async throws -> Void) async {
        let error = await #expect(throws: PersistenceError.self) {
            try await operation()
        }
        guard case .itemNotFound = error else {
            Issue.record("Expected PersistenceError.itemNotFound, got \(String(describing: error))")
            return
        }
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/Models/Sources/Models"
cat <<'PACKAGE_FILE_EOF' >"Packages/Models/Sources/Models/___VARIABLE_modelName___.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___.swift, created on __INIT_DATE__
//

import OversizeCore
import SwiftUI

public struct ___VARIABLE_modelName___: Identifiable, Equatable, Hashable, Sendable {
    public let id: UUID
    public let imageData: Data?
    public let name: String
    public let color: Color
    public let date: Date
    public let note: String?
    public let isFavorite: Bool
    public let isArchive: Bool

    public var image: Image? {
        imageData.flatMap { Image(data: $0) }
    }

    public init(
        id: UUID = UUID(),
        imageData: Data? = nil,
        name: String,
        color: Color,
        date: Date,
        note: String? = nil,
        isFavorite: Bool = false,
        isArchive: Bool = false
    ) {
        self.id = id
        self.imageData = imageData
        self.name = name
        self.color = color
        self.date = date
        self.note = note
        self.isFavorite = isFavorite
        self.isArchive = isArchive
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/Services/Sources/Services/Injection"
cat <<'PACKAGE_FILE_EOF' >"Packages/Services/Sources/Services/Injection/Injection.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// Injection.swift, created on __INIT_DATE__
//

import FactoryKit

public extension Container {
    var ___VARIABLE_modelVariableName___Service: Factory<___VARIABLE_modelName___Service> {
        self {
            ___VARIABLE_modelName___Service()
        }.cached
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/Services/Sources/Services/Services"
cat <<'PACKAGE_FILE_EOF' >"Packages/Services/Sources/Services/Services/___VARIABLE_modelName___Service.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___Service.swift, created on __INIT_DATE__
//

import Database
import FactoryKit
import Foundation
import Models
import SwiftUI

public actor ___VARIABLE_modelName___Service {
    @LazyInjected(\.storageService) private var storageService: ___VARIABLE_modelName___StorageService

    public init() {}

    public func ___VARIABLE_modelPluralVariableName___() async throws -> [___VARIABLE_modelName___] {
        try await storageService.fetch()
    }

    public func ___VARIABLE_modelVariableName___(id: UUID) async throws -> ___VARIABLE_modelName___ {
        try await storageService.fetch(id: id)
    }

    @discardableResult
    public func create(name: String, color: Color, date: Date = .now) async throws -> ___VARIABLE_modelName___ {
        let trimmedName = name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedName.isEmpty else {
            throw ___VARIABLE_modelName___ServiceError.emptyName
        }
        return try await storageService.save(___VARIABLE_modelName___(name: trimmedName, color: color, date: date))
    }

    public func delete(id: UUID) async throws {
        try await storageService.delete(id: id)
    }
}

public enum ___VARIABLE_modelName___ServiceError: Error, Equatable, Sendable {
    case emptyName
}
PACKAGE_FILE_EOF

mkdir -p "Packages/Services/Tests/ServicesTests"
cat <<'PACKAGE_FILE_EOF' >"Packages/Services/Tests/ServicesTests/___VARIABLE_modelName___ServiceTests.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___ServiceTests.swift, created on __INIT_DATE__
//

import FactoryKit
import FactoryTesting
import Models
@testable import Services
import SwiftUI
import Testing

@Suite(.container)
struct ___VARIABLE_modelName___ServiceTests {
    @Test func `create trims name and persists`() async throws {
        let service = Container.shared.___VARIABLE_modelVariableName___Service()

        let created = try await service.create(name: "  Music  ", color: .pink)
        let ___VARIABLE_modelPluralVariableName___ = try await service.___VARIABLE_modelPluralVariableName___()

        #expect(created.name == "Music")
        #expect(___VARIABLE_modelPluralVariableName___.map(\.id) == [created.id])
    }

    @Test func `create rejects empty name`() async throws {
        let service = Container.shared.___VARIABLE_modelVariableName___Service()

        await #expect(throws: ___VARIABLE_modelName___ServiceError.emptyName) {
            try await service.create(name: "   ", color: .pink)
        }
        #expect(try await service.___VARIABLE_modelPluralVariableName___().isEmpty)
    }

    @Test func `delete removes ___VARIABLE_modelVariableName___`() async throws {
        let service = Container.shared.___VARIABLE_modelVariableName___Service()
        let created = try await service.create(name: "Video", color: .red)

        try await service.delete(id: created.id)

        #expect(try await service.___VARIABLE_modelPluralVariableName___().isEmpty)
    }
}
PACKAGE_FILE_EOF

find Packages -name '*.swift' -type f -exec sed -i '' \
    -e "s/__INIT_DATE__/$TODAY/" \
    -e "s/__INIT_YEAR__/$YEAR/" {} +
