#!/bin/bash

# Generated by scripts/generate_init_scripts.py — Env and App sources.
# Do not edit by hand: change Packages/ and run `make init-scripts`.

set -euo pipefail

YEAR="${INIT_YEAR:-$(date +%Y)}"
TODAY="${INIT_DATE:-$(date +%d.%m.%Y)}"

mkdir -p "Packages/App/Sources/Main/Main"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Main/Main/MainModule.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// MainModule.swift, created on __INIT_DATE__
//

import OversizeArchitecture

@Module
public enum Main: ModuleProtocol {}

public struct MainInput: Sendable {}

public struct MainOutput: Sendable {}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Main/Main"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Main/Main/MainView.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// MainView.swift, created on __INIT_DATE__
//

import OversizeArchitecture
import OversizeKit
import OversizeNavigation
import OversizeNoticeKit
import OversizeResources
import OversizeUI
import SwiftUI

@View(module: Main.self)
public struct MainView: ViewProtocol {
    public var body: some View {
        NavigationLayout("Main") {
            content
        } background: {
            Color.backgroundSecondary
        }
        .contentMargins()
        .toolbarTitleDisplayMode(.inline)
        .toolbar { toolbarContent }
        .contentUnavailable(
            viewState.state,
            image: Illustration.Objects.Calendar.medium,
            title: "No ___VARIABLE_modelPluralVariableName___",
            subtitle: "Add your first ___VARIABLE_modelVariableName___"
        ) {
            Button("Add") {
                reducer.callAsFunction(.onTapAdd)
            }
        }
        .errorState(viewState.state)
        .navigationOpen($viewState.destination)
        .onAppear {
            reducer.callAsFunction(.onAppear)
        }
    }

    private var content: some View {
        VStack(spacing: .small) {
            NoticeListView()

            AdView()

            if let ___VARIABLE_modelPluralVariableName___ = viewState.state.result?.___VARIABLE_modelPluralVariableName___ {
                LazyVStack(spacing: .zero) {
                    ForEach(___VARIABLE_modelPluralVariableName___) { ___VARIABLE_modelVariableName___ in
                        ___VARIABLE_modelName___Row(___VARIABLE_modelVariableName___: ___VARIABLE_modelVariableName___) {
                            reducer.callAsFunction(.onTap___VARIABLE_modelName___(___VARIABLE_modelVariableName___))
                        }
                    }
                }
                .surfaceRadius(.medium)
            }
        }
    }

    @ToolbarContentBuilder
    private var toolbarContent: some ToolbarContent {
        ToolbarItem(placement: .confirmationAction) {
            Button("Add") {
                reducer.callAsFunction(.onTapAdd)
            }
            .labelStyle(.toolbar)
            .buttonStyle(.toolbarPrimary)
            .keyboardShortcut(.defaultAction)
        }
    }
}

#Preview {
    NavigationStack {
        Main.build()
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Main/Main"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Main/Main/MainViewModel.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// MainViewModel.swift, created on __INIT_DATE__
//

import FactoryKit
import Models
import OversizeArchitecture
import OversizeCore
import Services
import SwiftUI

@ViewModel(module: Main.self)
public actor MainViewModel: ViewModelProtocol {
    @Injected(\.___VARIABLE_modelVariableName___Service) private var ___VARIABLE_modelVariableName___Service: ___VARIABLE_modelName___Service

    func onAppear() async {
        let hasLoadedData = await state.state.result != nil
        await fetchData(showsLoading: !hasLoadedData)
    }

    func onTapAdd() async {
        let count = await state.state.result?.___VARIABLE_modelPluralVariableName___.count ?? 0
        let colors: [Color] = [.blue, .green, .orange, .pink, .purple]
        do {
            try await ___VARIABLE_modelVariableName___Service.create(
                name: "___VARIABLE_modelName___ \(count + 1)",
                color: colors[count % colors.count]
            )
            await fetchData(showsLoading: false)
        } catch {
            Log.error("Create ___VARIABLE_modelName___ failed:", error: error)
            await state.update { $0.state = .error(error) }
        }
    }

    func onTap___VARIABLE_modelName___(_ ___VARIABLE_modelVariableName___: ___VARIABLE_modelName___) async {
        await state.update {
            $0.destination = .detail(id: ___VARIABLE_modelVariableName___.id)
        }
    }
}

// MARK: - Helpers

private extension MainViewModel {
    func fetchData(showsLoading: Bool) async {
        if showsLoading {
            await state.update { $0.state = .loading }
        }
        do {
            let ___VARIABLE_modelPluralVariableName___ = try await ___VARIABLE_modelVariableName___Service.___VARIABLE_modelPluralVariableName___()
            await state.update { $0.state = .result(.init(___VARIABLE_modelPluralVariableName___: ___VARIABLE_modelPluralVariableName___)) }
        } catch {
            Log.error("Fetch ___VARIABLE_modelPluralVariableName___ failed:", error: error)
            await state.update { $0.state = .error(error) }
        }
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Main/Main"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Main/Main/MainViewState.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// MainViewState.swift, created on __INIT_DATE__
//

import Env
import Models
import Observation
import OversizeArchitecture
import OversizeCore

@Observable
public final class MainViewState: ViewStateProtocol {
    public var state: LoadingState<StateModel> = .idle
    public var destination: MainDestinations?

    public init(input _: Main.Input?) {}
}

// MARK: - Supporting types

public extension MainViewState {
    struct StateModel: Emptyable {
        public let ___VARIABLE_modelPluralVariableName___: [___VARIABLE_modelName___]

        public var isEmpty: Bool {
            ___VARIABLE_modelPluralVariableName___.isEmpty
        }
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Main/Main/Subviews"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Main/Main/Subviews/___VARIABLE_modelName___Row.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___Row.swift, created on __INIT_DATE__
//

import Models
import OversizeUI
import SwiftUI

struct ___VARIABLE_modelName___Row: View {
    private let ___VARIABLE_modelVariableName___: ___VARIABLE_modelName___
    private let action: () -> Void

    init(___VARIABLE_modelVariableName___: ___VARIABLE_modelName___, action: @escaping () -> Void) {
        self.___VARIABLE_modelVariableName___ = ___VARIABLE_modelVariableName___
        self.action = action
    }

    var body: some View {
        Row(
            ___VARIABLE_modelVariableName___.name,
            subtitle: ___VARIABLE_modelVariableName___.date.formatted(date: .abbreviated, time: .omitted),
            action: action,
            leading: {
                Circle()
                    .fill(___VARIABLE_modelVariableName___.color)
                    .frame(width: 24, height: 24)
            }
        )
        .navigatable()
        .buttonStyle(.row)
    }
}

#Preview {
    ___VARIABLE_modelName___Row(
        ___VARIABLE_modelVariableName___: ___VARIABLE_modelName___(name: "Music", color: .pink, date: .now)
    ) {}
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Main/___VARIABLE_modelName___Detail"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Main/___VARIABLE_modelName___Detail/___VARIABLE_modelName___Detail.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___Detail.swift, created on __INIT_DATE__
//

import Foundation
import OversizeArchitecture

@Module
public enum ___VARIABLE_modelName___Detail: ModuleProtocol {}

public struct ___VARIABLE_modelName___DetailInput: Sendable {
    public let id: UUID

    public init(id: UUID) {
        self.id = id
    }
}

public struct ___VARIABLE_modelName___DetailOutput: Sendable {}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Main/___VARIABLE_modelName___Detail"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Main/___VARIABLE_modelName___Detail/___VARIABLE_modelName___DetailView.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___DetailView.swift, created on __INIT_DATE__
//

import Models
import OversizeArchitecture
import OversizeNavigation
import OversizeUI
import SwiftUI

@View(module: ___VARIABLE_modelName___Detail.self)
public struct ___VARIABLE_modelName___DetailView: ViewProtocol {
    public var body: some View {
        NavigationLayout(viewState.state.result?.name ?? "") {
            content
        } background: {
            Color.backgroundSecondary
        }
        .contentMargins()
        .toolbarTitleDisplayMode(.inline)
        .errorState(viewState.state)
        .task {
            reducer.callAsFunction(.onAppear)
        }
    }

    @ViewBuilder
    private var content: some View {
        if let ___VARIABLE_modelVariableName___ = viewState.state.result {
            VStack(spacing: .zero) {
                Row("Name", subtitle: ___VARIABLE_modelVariableName___.name, leading: {
                    Circle()
                        .fill(___VARIABLE_modelVariableName___.color)
                        .frame(width: 24, height: 24)
                })

                Row("Date", subtitle: ___VARIABLE_modelVariableName___.date.formatted(date: .long, time: .omitted))

                if let note = ___VARIABLE_modelVariableName___.note {
                    Row("Note", subtitle: note)
                }
            }
            .surfaceRadius(.medium)
        }
    }
}

#Preview {
    NavigationStack {
        ___VARIABLE_modelName___Detail.build(input: .init(id: UUID()))
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Main/___VARIABLE_modelName___Detail"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Main/___VARIABLE_modelName___Detail/___VARIABLE_modelName___DetailViewModel.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___DetailViewModel.swift, created on __INIT_DATE__
//

import FactoryKit
import OversizeArchitecture
import OversizeCore
import Services

@ViewModel(module: ___VARIABLE_modelName___Detail.self)
public actor ___VARIABLE_modelName___DetailViewModel: ViewModelProtocol {
    @Injected(\.___VARIABLE_modelVariableName___Service) private var ___VARIABLE_modelVariableName___Service: ___VARIABLE_modelName___Service

    func onAppear() async {
        guard let id = await state.___VARIABLE_modelVariableName___Id else {
            await state.update { $0.state = .error(PersistenceError.itemNotFound) }
            return
        }
        do {
            let ___VARIABLE_modelVariableName___ = try await ___VARIABLE_modelVariableName___Service.___VARIABLE_modelVariableName___(id: id)
            await state.update { $0.state = .result(___VARIABLE_modelVariableName___) }
        } catch {
            Log.error("Fetch ___VARIABLE_modelName___ \(id) failed:", error: error)
            await state.update { $0.state = .error(error) }
        }
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Main/___VARIABLE_modelName___Detail"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Main/___VARIABLE_modelName___Detail/___VARIABLE_modelName___DetailViewState.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___DetailViewState.swift, created on __INIT_DATE__
//

import Foundation
import Models
import Observation
import OversizeArchitecture
import OversizeCore

@Observable
public final class ___VARIABLE_modelName___DetailViewState: ViewStateProtocol {
    public var state: LoadingState<___VARIABLE_modelName___> = .idle

    public let ___VARIABLE_modelVariableName___Id: UUID?

    public init(input: ___VARIABLE_modelName___Detail.Input?) {
        ___VARIABLE_modelVariableName___Id = input?.id
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Onboarding/OnboardingGreeting"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Onboarding/OnboardingGreeting/OnboardingGreeting.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// OnboardingGreeting.swift, created on __INIT_DATE__
//

import OversizeArchitecture

@Module
public enum OnboardingGreeting: ModuleProtocol {}

public struct OnboardingGreetingInput: Sendable {}

public struct OnboardingGreetingOutput: Sendable {}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Onboarding/OnboardingGreeting"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Onboarding/OnboardingGreeting/OnboardingGreetingView.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// OnboardingGreetingView.swift, created on __INIT_DATE__
//

import OversizeArchitecture
import OversizeNavigation
import OversizeOnboardingKit
import OversizeServices
import OversizeUI
import SwiftUI

@View(module: OnboardingGreeting.self)
public struct OnboardingGreetingView: ViewProtocol {
    public var body: some View {
        OnboardView(
            content: {
                content
            },
            actions: {
                actions
            }
        )
        .navigationOpen($viewState.destination)
    }

    var content: some View {
        VStack(spacing: .large) {
            Spacer()

            if let image = Info.App.icon {
                image
                    .resizable()
                    .frame(width: 96, height: 96)
                    .mask(RoundedRectangle(
                        cornerRadius: 22,
                        style: .continuous
                    ))
            } else {
                RoundedRectangle(cornerRadius: 22, style: .continuous)
                    .fill(Color.gray)
                    .frame(width: 96, height: 96)
            }

            VStack(spacing: .small) {
                Text("Welcome")
                    .largeTitle()

                Text("All your information in one app")
                    .title2(.semibold)
                    .foregroundStyle(.secondary)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, .large)
            }

            Spacer()
        }
    }

    var actions: some View {
        Button("Get Started") {
            reducer.callAsFunction(.onTapContinue)
        }
        .buttonStyle(.primary)
        .controlSize(.large)
        .accent()
    }
}

#Preview {
    NavigationStack {
        OnboardingGreeting.build()
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Onboarding/OnboardingGreeting"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Onboarding/OnboardingGreeting/OnboardingGreetingViewModel.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// OnboardingGreetingViewModel.swift, created on __INIT_DATE__
//

import OversizeArchitecture

@ViewModel(module: OnboardingGreeting.self)
public actor OnboardingGreetingViewModel: ViewModelProtocol {
    func onTapContinue() async {
        await state.update {
            $0.destination = .setup
        }
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Onboarding/OnboardingGreeting"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Onboarding/OnboardingGreeting/OnboardingGreetingViewState.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// OnboardingGreetingViewState.swift, created on __INIT_DATE__
//

import Env
import Observation
import OversizeArchitecture
import SwiftUI

@Observable
public final class OnboardingGreetingViewState: ViewStateProtocol {
    public var destination: OnboardingDestinations?

    public init(input _: OnboardingGreeting.Input?) {}
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Onboarding/OnboardingSetup"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Onboarding/OnboardingSetup/OnboardingSetup.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// OnboardingSetup.swift, created on __INIT_DATE__
//

import OversizeArchitecture

@Module
public enum OnboardingSetup: ModuleProtocol {}

public struct OnboardingSetupInput: Sendable {}

public struct OnboardingSetupOutput: Sendable {}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Onboarding/OnboardingSetup"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Onboarding/OnboardingSetup/OnboardingSetupView.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// OnboardingSetupView.swift, created on __INIT_DATE__
//

import OversizeArchitecture
import OversizeNavigation
import OversizeOnboardingKit
import OversizeUI
import SwiftUI

@View(module: OnboardingSetup.self)
public struct OnboardingSetupView: ViewProtocol {
    @FocusState private var focusedField: OnboardingSetupViewState.FocusField?

    public var body: some View {
        OnboardView(
            content: {
                content
            },
            actions: {
                actions
            }
        )
        .onAppear { focusedField = .firstText }
    }

    var content: some View {
        ScrollView {
            VStack(spacing: .large) {
                VStack(spacing: .xSmall) {
                    Text("Setup")
                        .title2()

                    Text("Enter your basic settings")
                        .body(.semibold)
                        .foregroundStyle(.secondary)
                        .multilineTextAlignment(.center)
                        .padding(.horizontal, .large)
                }

                VStack(spacing: .small) {
                    firstTextField

                    secondTextField
                }
                .fieldLabelPosition(.overInput)
            }
        }
        .contentMargins()
    }

    private var firstTextField: some View {
        TextField("First text", text: $viewState.firstText)
            .textFieldStyle(.placeholder("First text", text: $viewState.firstText))
            .submitLabel(.next)
            .onSubmit { focusedField = .secondText }
            .focused($focusedField, equals: .firstText)
    }

    private var secondTextField: some View {
        TextField("Second text", text: $viewState.secondText)
            .textFieldStyle(.placeholder("Second text", text: $viewState.secondText))
            .submitLabel(.continue)
            .onSubmit { reducer.callAsFunction(.onTapContinue) }
            .focused($focusedField, equals: .secondText)
    }

    var actions: some View {
        Button("Continue") {
            reducer.callAsFunction(.onTapContinue)
        }
        .buttonStyle(.primary)
        .controlSize(.large)
        .accent()
    }
}

#Preview {
    NavigationStack {
        OnboardingSetup.build()
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Onboarding/OnboardingSetup"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Onboarding/OnboardingSetup/OnboardingSetupViewModel.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// OnboardingSetupViewModel.swift, created on __INIT_DATE__
//

import FactoryKit
import Foundation
import OversizeArchitecture
import OversizeServices

@ViewModel(module: OnboardingSetup.self)
public actor OnboardingSetupViewModel: ViewModelProtocol {
    @Injected(\.appStateService) private var appStateService: AppStateService

    func onTapContinue() async {
        appStateService.completedOnboarding()
        CFPreferencesAppSynchronize(kCFPreferencesCurrentApplication)
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Onboarding/OnboardingSetup"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Onboarding/OnboardingSetup/OnboardingSetupViewState.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// OnboardingSetupViewState.swift, created on __INIT_DATE__
//

import Observation
import OversizeArchitecture

@Observable
public final class OnboardingSetupViewState: ViewStateProtocol {
    public var firstText: String = ""
    public var secondText: String = ""

    public init(input _: OnboardingSetup.Input?) {}
}

// MARK: - Supporting types

public extension OnboardingSetupViewState {
    enum FocusField: Hashable, Sendable {
        case firstText
        case secondText
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Settings/AppSettings"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Settings/AppSettings/AppSettings.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// AppSettings.swift, created on __INIT_DATE__
//

import OversizeArchitecture

@Module
public enum AppSettings: ModuleProtocol {}

public struct AppSettingsInput: Sendable {}

public struct AppSettingsOutput: Sendable {}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Settings/AppSettings"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Settings/AppSettings/AppSettingsView.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// AppSettingsView.swift, created on __INIT_DATE__
//

import OversizeArchitecture
import OversizeKit
import OversizeNavigation
import OversizeResources
import OversizeUI
import SwiftUI

@View(module: AppSettings.self)
public struct AppSettingsView: ViewProtocol {
    public var body: some View {
        SettingsView {
            Row("___VARIABLE_modelName___ settings") {
                reducer.callAsFunction(.onTap___VARIABLE_modelName___Settings)
            } leading: {
                Image.Base.setting.icon()
            }
            .navigatable()
            .buttonStyle(.row)
        }
        .navigationOpen($viewState.destination)
    }
}

#Preview {
    NavigationStack {
        AppSettings.build()
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Settings/AppSettings"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Settings/AppSettings/AppSettingsViewModel.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// AppSettingsViewModel.swift, created on __INIT_DATE__
//

import OversizeArchitecture

@ViewModel(module: AppSettings.self)
public actor AppSettingsViewModel: ViewModelProtocol {
    func onTap___VARIABLE_modelName___Settings() async {
        await state.update {
            $0.destination = .___VARIABLE_modelVariableName___Settings
        }
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Settings/AppSettings"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Settings/AppSettings/AppSettingsViewState.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// AppSettingsViewState.swift, created on __INIT_DATE__
//

import Env
import Observation
import OversizeArchitecture

@Observable
public final class AppSettingsViewState: ViewStateProtocol {
    public var destination: AppSettingsDestinations?

    public init(input _: AppSettings.Input?) {}
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Settings/___VARIABLE_modelName___Settings"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Settings/___VARIABLE_modelName___Settings/___VARIABLE_modelName___Settings.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___Settings.swift, created on __INIT_DATE__
//

import OversizeArchitecture

@Module
public enum ___VARIABLE_modelName___Settings: ModuleProtocol {}

public struct ___VARIABLE_modelName___SettingsInput: Sendable {}

public struct ___VARIABLE_modelName___SettingsOutput: Sendable {}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Settings/___VARIABLE_modelName___Settings"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Settings/___VARIABLE_modelName___Settings/___VARIABLE_modelName___SettingsView.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___SettingsView.swift, created on __INIT_DATE__
//

import OversizeArchitecture
import OversizeNavigation
import OversizeUI
import SwiftUI

@View(module: ___VARIABLE_modelName___Settings.self)
public struct ___VARIABLE_modelName___SettingsView: ViewProtocol {
    public var body: some View {
        NavigationLayout("___VARIABLE_modelName___ settings") {
            content
        } background: {
            Color.backgroundSecondary
        }
        .toolbarTitleDisplayMode(.inline)
    }

    var content: some View {
        Section {
            Row("App settings") {} leading: {
                Image.Base.edit.icon()
            }
        }
    }
}

#Preview {
    NavigationStack {
        ___VARIABLE_modelName___Settings.build()
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Settings/___VARIABLE_modelName___Settings"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Settings/___VARIABLE_modelName___Settings/___VARIABLE_modelName___SettingsViewModel.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___SettingsViewModel.swift, created on __INIT_DATE__
//

import OversizeArchitecture

@ViewModel(module: ___VARIABLE_modelName___Settings.self)
public actor ___VARIABLE_modelName___SettingsViewModel: ViewModelProtocol {}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Sources/Settings/___VARIABLE_modelName___Settings"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Sources/Settings/___VARIABLE_modelName___Settings/___VARIABLE_modelName___SettingsViewState.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// ___VARIABLE_modelName___SettingsViewState.swift, created on __INIT_DATE__
//

import Observation
import OversizeArchitecture
import SwiftUI

@Observable
public final class ___VARIABLE_modelName___SettingsViewState: ViewStateProtocol {
    public init(input _: ___VARIABLE_modelName___Settings.Input?) {}
}
PACKAGE_FILE_EOF

mkdir -p "Packages/App/Tests/MainTests"
cat <<'PACKAGE_FILE_EOF' >"Packages/App/Tests/MainTests/MainViewModelTests.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// MainViewModelTests.swift, created on __INIT_DATE__
//

import FactoryKit
import FactoryTesting
@testable import Main
import Services
import SwiftUI
import Testing

@Suite(.container)
@MainActor
struct MainViewModelTests {
    @Test func `on appear loads ___VARIABLE_modelPluralVariableName___`() async throws {
        let created = try await Container.shared.___VARIABLE_modelVariableName___Service().create(name: "Music", color: .pink)
        let state = MainViewState(input: nil)
        let viewModel = MainViewModel(state: state, input: nil, output: nil)

        await viewModel.handleAction(.onAppear)

        #expect(state.state.result?.___VARIABLE_modelPluralVariableName___.map(\.id) == [created.id])
    }

    @Test func `on tap add creates ___VARIABLE_modelVariableName___`() async {
        let state = MainViewState(input: nil)
        let viewModel = MainViewModel(state: state, input: nil, output: nil)

        await viewModel.handleAction(.onAppear)
        await viewModel.handleAction(.onTapAdd)

        #expect(state.state.result?.___VARIABLE_modelPluralVariableName___.map(\.name) == ["___VARIABLE_modelName___ 1"])
    }

    @Test func `on tap ___VARIABLE_modelVariableName___ opens detail`() async throws {
        let created = try await Container.shared.___VARIABLE_modelVariableName___Service().create(name: "Music", color: .pink)
        let state = MainViewState(input: nil)
        let viewModel = MainViewModel(state: state, input: nil, output: nil)

        await viewModel.handleAction(.onTap___VARIABLE_modelName___(created))

        #expect(state.destination == .detail(id: created.id))
    }
}
PACKAGE_FILE_EOF

mkdir -p "Packages/Env/Sources/Env/Destinations"
cat <<'PACKAGE_FILE_EOF' >"Packages/Env/Sources/Env/Destinations/AppSettingsDestinations.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// AppSettingsDestinations.swift, created on __INIT_DATE__
//

import Foundation

public nonisolated enum AppSettingsDestinations: Hashable, Sendable {
    case ___VARIABLE_modelVariableName___Settings
}
PACKAGE_FILE_EOF

mkdir -p "Packages/Env/Sources/Env/Destinations"
cat <<'PACKAGE_FILE_EOF' >"Packages/Env/Sources/Env/Destinations/MainDestinations.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// MainDestinations.swift, created on __INIT_DATE__
//

import Foundation

public nonisolated enum MainDestinations: Hashable, Sendable {
    case detail(id: UUID)
}
PACKAGE_FILE_EOF

mkdir -p "Packages/Env/Sources/Env/Destinations"
cat <<'PACKAGE_FILE_EOF' >"Packages/Env/Sources/Env/Destinations/OnboardingDestinations.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// OnboardingDestinations.swift, created on __INIT_DATE__
//

import Foundation

public nonisolated enum OnboardingDestinations: Hashable, Sendable {
    case setup
}
PACKAGE_FILE_EOF

mkdir -p "Packages/Env/Sources/Env/Tabs"
cat <<'PACKAGE_FILE_EOF' >"Packages/Env/Sources/Env/Tabs/RootTabs.swift"
//
// Copyright © __INIT_YEAR__ ___FULLUSERNAME___
// RootTabs.swift, created on __INIT_DATE__
//

import OversizeResources
import OversizeUI
import SwiftUI

public nonisolated enum RootTabs: Int, Codable, Sendable {
    case main
    case settings
}

extension RootTabs: Identifiable {
    public static var tabs: [RootTabs] {
        [.main, .settings]
    }

    public var icon: Image {
        switch self {
        case .main:
            Image.Base.Home.fill
        case .settings:
            Image.Base.Setting.fill
        }
    }

    public var title: LocalizedStringResource {
        switch self {
        case .main:
            "Main"
        case .settings:
            "Settings"
        }
    }

    public var id: String {
        "\(self)"
    }
}
PACKAGE_FILE_EOF

find Packages -name '*.swift' -type f -exec sed -i '' \
    -e "s/__INIT_DATE__/$TODAY/" \
    -e "s/__INIT_YEAR__/$YEAR/" {} +
